### ISSUE TITLE
Menu links

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2017.djangocon.us#107]
We have had a few usability complaints about our top menu not being obvious that the top most levels are meant to be clicked. I see the triangle and I sort-of see the complaint. I think an easy fix is to repeat the top link as a first level link and update the copy.

Example:
Sponsors: [Become a Sponsor] => Sponsors: [Our Sponsors, Become a Sponsor]

Since y'all did the usability work, does this sound reasonable? We can make this change ourselves, but I wanted to run it by you in case there's a better solution.

**Comment by kkellydesign** [comment]
It's a valid complaint – I noticed that as well a couple days ago. It's especially a problem on mobile where there's no way to get to the top-level pages if they have a subpage. I think your solution is probably best – just repeat the links as the first item in the subnav list. Do you agree @mtrythall?

**Comment by mtrythall** [comment]
Age old problem.

I think the additional links might be needed for mobile given the part of Foundation we're using. I'm not thrilled about adding the links on desktop just because this is a pattern that's over a decade old and easily learned. We even provide different types of links in the nav so that the behavior is easily discovered.

If we do add new links to desktop, I'd want those link titles to be different than the top level. Your example speaks to that, Jeff, where it's Sponsors > Our Sponsors. I wouldn't want About > About.

Let's try it on mobile and see how it feels.

**Comment by kkellydesign** [comment]
So for mobile-only duplicate links, you'd just add this to the subnav: 

`<li class="hide-for-medium">etc..</li>`

**Comment by jefftriplett** [comment]
Thanks for the advice. To address the immediate issue, I cloned the top links and matched their menu item text with the page's heading. If it bothers anyone we can try the `hide-for-medium` suggestion to selectively show them. I agree that people should know by now, but if we have to train people to use the menus then we might be fighting more of an uphill battle than we want. Thanks again.
