### ISSUE TITLE
Hide "See full schedule" button on About 

### ISSUE THREAD

**Issue by williln** [djangocon/2017.djangocon.us#25]
Page: `about/`

Comment out the "See full schedule" button, as we do not yet have a schedule. 

<img width="531" alt="screen shot 2017-03-03 at 9 01 45 am" src="https://cloud.githubusercontent.com/assets/2286304/23560688/2ca82ef6-fff0-11e6-842c-9fa4771d077f.png">

**Comment by Nandutu** [comment]
@williln i can't find the about page or related information . Any references

**Comment by KatherineMichel** [comment]
Hi @Nandutu, Thank you for your question. It is in the design branch, _layouts folder, about.html file, line #123. I have put a direct link below. We also have contribution guidance in the design branch README. Link also below. The guidance is new (I wrote most of it). Please let us know if you have questions or feedback. 
https://github.com/djangocon/2017.djangocon.us/blob/design/_layouts/about.html#L123
https://github.com/djangocon/2017.djangocon.us/blob/design/README.md

**Comment by Nandutu** [comment]
@KatherineMichel just commented out the button, though i should be having issues with pull requests, seem to have done it wrong. kindly look at my reference above.

Thanks

**Comment by KatherineMichel** [comment]
@Nandutu I tested your update locally and it looked great. I've also had a problem similar to yours with submitting a pull request. I've been told it happens if the pull request is submitted via the main repo instead of the forked repo. Maybe I should add some guidance to the README.

**Comment by KatherineMichel** [comment]
@Nandutu I closed the open pull request.

**Comment by Nandutu** [comment]
@KatherineMichel thanks, good to know it worked locally.

**Comment by Nandutu** [comment]
@KatherineMichel each time am trying to fork this repo, i cant get a copy and this applies to only repos in djangocon org where i am a member.  Is there a way i can be helped
Thanks

**Comment by KatherineMichel** [comment]
Hi @Nandutu, sorry that a problem is happening. Apparently this is a new problem since you were able to submit a PR the other day? I tried to fork a couple of the DjangoCon repos and was able to, but it did tell me that I already had a copy but I didn't, which doesn't seem normal. I asked around among the developer and we're not sure what is causing this. We recommend that you make sure that you are logged in and contact GitHub support to submit an issue. Perhaps in the meantime it is a production bug that they will resolve. Let us know what happens and if I get new info I'll let you know.
