### ISSUE TITLE
Update the style guide

### ISSUE THREAD

**Issue by williln** [djangocon/2017.djangocon.us#80]
Like... how a button is styled, for example.

**Comment by mtrythall** [comment]
Remember, the site is built on Foundation:

http://foundation.zurb.com/sites/docs/button.html

**Comment by KatherineMichel** [comment]
I will take a look at the docs when I get the chance. @williln @mtrythall

**Comment by KatherineMichel** [comment]
Might also be useful to have a bit of a layout explainer to give guidance for which template(s) (base, default, .md, etc.) to use based on which layout someone wants to put together ...? Could help to standardize the code from page to page.

**Comment by mtrythall** [comment]
I can't speak to what should be .md and what shouldn't. That depends on how you folks want to set it up. I tend to avoid Markdown and think it's only useful when you have very, very simple content.

default.html inherits from base.html (like everything else), except that default.html provides wrappers for content and a header. Typically you'd use default.html for sub pages or anything fairly basic where you want the content centered and ready to use a grid. Content that is full width (like colored page blocks found on Venue) or has something more custom, you'll want to use base.

Basically: if you just want to drop in basic content and want left and right gutters, content centered, use default.html. You can't go window edge-to-window edge with default.html.

The other layouts are all pretty specific, unique even, and I doubt you'd reuse them. Their names are also generally self-explanatory, e.g. events.html for Events, schedule.html for the schedule, etc.

The only confusing name is post-list, which should probably be news-list since that's what the site is using.

I'm happy to document it, but there isn't much to say. default.html is only a few lines of code layout-wise.

**Comment by KatherineMichel** [comment]
Ok, thank you. Even if not much to stay, I think still good to document. Might be info that is helpful to  people who are newcomers to the project.
